"""new msg

Revision ID: 14edd2132871
Revises: 6173b12c8985
Create Date: 2023-03-02 19:55:33.800144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14edd2132871'
down_revision = '6173b12c8985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('msg_text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('msg')
    # ### end Alembic commands ###
